  add-max-file-size-note-86[m
  chore/fix-format-layout[m
  develop[m
  feature/add-name-placeholder[m
  feature/created-notes-section[m
  feature/created-notes-section-v2[m
* [32mfeature/duplicate-report-prevention-164[m
  feature/max-file-size-hint[m
  feature/mobile-text-centering[m
  feature/upload-max-size-hint[m
  fix/create-note-responsive-89[m
  fix/delete-account-permanently-typo[m
  fix/filecard-author-display[m
  fix/filecard-author-name[m
  fix/filesgrid-author-metadata[m
  fix/mobile-text-centering[m
  fix/settings-header-gradient[m
  issue-86-max-file-size-note[m
  main[m
  pr-125[m
